events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        charset utf-8;
        
        location / {
            try_files $uri $uri/ =404;
        }
        
        location /secondpage {
            return 200 "<h1>Second Page</h1>";
            add_header Content-Type text/html;
        }
        
        location /music {
            alias /usr/share/nginx/music;
            add_header Content-Disposition 'attachment; filename="song.mp3"';
        }
    }
}
